// Dev-seed questions — Phase 2 bootstrap, scaled in Phase 4b. All marked
// source:"dev-seed". These are UNREVIEWED and will be replaced by approved
// content in Phase 10. 8 categories × 3 difficulties × 2 languages × 5 each =
// 240 questions total (≥100/language — the Gate A bank-size bar, doc 11).
//
// correctIx refers to the correct answer in the `answers` array BEFORE shuffling.
// The serving engine (questionBank.ts) shuffles answer order on each serve.

export type SeedDifficulty = "easy" | "medium" | "hard";
export type SeedLanguage = "he" | "en";

export interface SeedQuestion {
  text: string;
  answers: [string, string, string, string];
  correctIx: 0 | 1 | 2 | 3;
  difficulty: SeedDifficulty;
  language: SeedLanguage;
  category: string;
}

export const SEED_QUESTIONS: SeedQuestion[] = [
  // ──────────────────────────────────────────────────────────
  // HE — general_knowledge
  // ──────────────────────────────────────────────────────────
  {
    text: "מהו הצבע הנפוץ ביותר בדגלי מדינות העולם?",
    answers: ["אדום", "כחול", "ירוק", "לבן"],
    correctIx: 0,
    difficulty: "easy",
    language: "he",
    category: "general_knowledge",
  },
  {
    text: "כמה ימים יש בשנה שאינה מעוברת?",
    answers: ["365", "366", "364", "360"],
    correctIx: 0,
    difficulty: "easy",
    language: "he",
    category: "general_knowledge",
  },
  {
    text: "מהו הכוכב הקרוב ביותר לכדור הארץ מלבד השמש?",
    answers: ["פרוקסימה קנטאורי", "סיריוס", "ואגה", "אלטאיר"],
    correctIx: 0,
    difficulty: "medium",
    language: "he",
    category: "general_knowledge",
  },
  {
    text: "כמה שפות רשמיות יש לשוויץ?",
    answers: ["4", "3", "2", "5"],
    correctIx: 0,
    difficulty: "medium",
    language: "he",
    category: "general_knowledge",
  },
  {
    text: "מהו היסוד הכימי עם המספר האטומי 79?",
    answers: ["זהב", "כסף", "פלטינה", "נחושת"],
    correctIx: 0,
    difficulty: "hard",
    language: "he",
    category: "general_knowledge",
  },
  {
    text: "בן כמה היה מוצרט כאשר כתב את הסימפוניה הראשונה שלו?",
    answers: ["8", "12", "6", "10"],
    correctIx: 0,
    difficulty: "hard",
    language: "he",
    category: "general_knowledge",
  },

  // ──────────────────────────────────────────────────────────
  // HE — sports
  // ──────────────────────────────────────────────────────────
  {
    text: "כמה שחקנים של כל קבוצה נמצאים על מגרש הכדורגל בכל עת?",
    answers: ["11", "10", "12", "9"],
    correctIx: 0,
    difficulty: "easy",
    language: "he",
    category: "sports",
  },
  {
    text: "כמה נקודות מקבלים על טאצ'-דאון בכדורגל אמריקאי?",
    answers: ["6", "3", "7", "4"],
    correctIx: 0,
    difficulty: "easy",
    language: "he",
    category: "sports",
  },
  {
    text: "באיזו עיר נערכו אולימפיאדת הקיץ 2020 (שהתקיימה ב-2021)?",
    answers: ["טוקיו", "פריז", "לונדון", "ריו דה ז'ניירו"],
    correctIx: 0,
    difficulty: "medium",
    language: "he",
    category: "sports",
  },
  {
    text: "כמה תארי גרנד-סלאם כבש נובק ג'וקוביץ' נכון לסוף 2023?",
    answers: ["24", "22", "20", "23"],
    correctIx: 0,
    difficulty: "medium",
    language: "he",
    category: "sports",
  },
  {
    text: "מי מחזיקה בשיא העולם בריצת 100 מטר לנשים (10.49 שניות)?",
    answers: [
      "פלורנס גריפית'-ג'וינר",
      "שלי-אן פרייזר-פרייס",
      "עלייה אלי",
      "מרלין אוטי",
    ],
    correctIx: 0,
    difficulty: "hard",
    language: "he",
    category: "sports",
  },
  {
    text: "באיזה ספורט מחזיקה ישראל במדליית זהב אולימפית היסטורית ראשונה (2021)?",
    answers: ["ג'ודו", "שחייה", "גלישה", "רכיבה אומנותית"],
    correctIx: 0,
    difficulty: "hard",
    language: "he",
    category: "sports",
  },

  // ──────────────────────────────────────────────────────────
  // HE — movies_tv
  // ──────────────────────────────────────────────────────────
  {
    text: "מי ביים את הסרט 'שינדלר'ס ליסט'?",
    answers: ["סטיבן ספילברג", "מרטין סקורסזה", "רידלי סקוט", "ג'יימס קמרון"],
    correctIx: 0,
    difficulty: "easy",
    language: "he",
    category: "movies_tv",
  },
  {
    text: "מי כיכב בתפקיד ג'ק דוסון בסרט 'טיטאניק' (1997)?",
    answers: ["ליאונרדו דיקפריו", "ברד פיט", "מאט דיימון", "ג'וני דפ"],
    correctIx: 0,
    difficulty: "easy",
    language: "he",
    category: "movies_tv",
  },
  {
    text: "כמה סרטים עיקריים יש בטרילוגיית 'שר הטבעות' של פיטר ג'קסון?",
    answers: ["3", "2", "4", "6"],
    correctIx: 0,
    difficulty: "medium",
    language: "he",
    category: "movies_tv",
  },
  {
    text: "באיזה עיר אמריקאית מתרחשת עלילת הסדרה 'The Wire'?",
    answers: ["בולטימור", "ניו יורק", "שיקגו", "לוס אנג'לס"],
    correctIx: 0,
    difficulty: "medium",
    language: "he",
    category: "movies_tv",
  },
  {
    text: "מי זכה בפרס אוסקר לבמאי הטוב ביותר על הסרט 'פרזיטים' (2019)?",
    answers: ["בונג ג'ון-הו", "מרטין סקורסזה", "סם מנדס", "קוונטין טרנטינו"],
    correctIx: 0,
    difficulty: "hard",
    language: "he",
    category: "movies_tv",
  },
  {
    text: "באיזו שנה יצא לאקרנים הסרט '2001: A Space Odyssey' של קובריק?",
    answers: ["1968", "1972", "1965", "1970"],
    correctIx: 0,
    difficulty: "hard",
    language: "he",
    category: "movies_tv",
  },

  // ──────────────────────────────────────────────────────────
  // HE — music
  // ──────────────────────────────────────────────────────────
  {
    text: "כמה חברים היו בהרכב 'הביטלס'?",
    answers: ["4", "3", "5", "2"],
    correctIx: 0,
    difficulty: "easy",
    language: "he",
    category: "music",
  },
  {
    text: "מי כתב את הסימפוניה התשיעית הכוללת את 'שמחה לעולם'?",
    answers: ["בטהובן", "מוצרט", "שופן", "בראמס"],
    correctIx: 0,
    difficulty: "easy",
    language: "he",
    category: "music",
  },
  {
    text: "באיזו מדינה נולד פרדי מרקורי (מוקאן)?",
    answers: ["זנזיבר / טנזניה", "אנגליה", "הודו", "פקיסטן"],
    correctIx: 0,
    difficulty: "medium",
    language: "he",
    category: "music",
  },
  {
    text: "מהו האלבום הנמכר ביותר בהיסטוריה?",
    answers: [
      "Thriller — מייקל ג'קסון",
      "Back in Black — AC/DC",
      "The Dark Side of the Moon — פינק פלויד",
      "Led Zeppelin IV",
    ],
    correctIx: 0,
    difficulty: "medium",
    language: "he",
    category: "music",
  },
  {
    text: "כמה סימפוניות כתב יוהאנס ברהמס?",
    answers: ["4", "9", "5", "6"],
    correctIx: 0,
    difficulty: "hard",
    language: "he",
    category: "music",
  },
  {
    text: "באיזו שנה נוסדה להקת 'לד זפלין'?",
    answers: ["1968", "1970", "1965", "1972"],
    correctIx: 0,
    difficulty: "hard",
    language: "he",
    category: "music",
  },

  // ──────────────────────────────────────────────────────────
  // HE — science_tech
  // ──────────────────────────────────────────────────────────
  {
    text: "מהי הפלנטה הקרובה ביותר לשמש?",
    answers: ["מרקורי", "ונוס", "מאדים", "כדור הארץ"],
    correctIx: 0,
    difficulty: "easy",
    language: "he",
    category: "science_tech",
  },
  {
    text: "מהי הנוסחה הכימית של מים?",
    answers: ["H₂O", "CO₂", "O₂", "H₂"],
    correctIx: 0,
    difficulty: "easy",
    language: "he",
    category: "science_tech",
  },
  {
    text: "כמה כרומוזומים יש בתא אנושי רגיל (דיפלואידי)?",
    answers: ["46", "48", "44", "23"],
    correctIx: 0,
    difficulty: "medium",
    language: "he",
    category: "science_tech",
  },
  {
    text: "מהו גיל כדור הארץ בקירוב (במיליארדי שנים)?",
    answers: ["4.5", "2.5", "6.5", "3.5"],
    correctIx: 0,
    difficulty: "medium",
    language: "he",
    category: "science_tech",
  },
  {
    text: "מה מהירות האור בריק (בקירוב)?",
    answers: [
      "300,000 ק\"מ בשנייה",
      "150,000 ק\"מ בשנייה",
      "450,000 ק\"מ בשנייה",
      "200,000 ק\"מ בשנייה",
    ],
    correctIx: 0,
    difficulty: "hard",
    language: "he",
    category: "science_tech",
  },
  {
    text: "מה הוא עקרון אי-הוודאות של היינזנברג?",
    answers: [
      "לא ניתן לדעת במדויק גם מיקום וגם תנע של חלקיק בו-זמנית",
      "האור מתנהג גם כגל וגם כחלקיק",
      "מסה ואנרגיה שקולות",
      "שני אלקטרונים לא יכולים להיות באותו מצב קוונטי",
    ],
    correctIx: 0,
    difficulty: "hard",
    language: "he",
    category: "science_tech",
  },

  // ──────────────────────────────────────────────────────────
  // HE — history
  // ──────────────────────────────────────────────────────────
  {
    text: "באיזו שנה קמה מדינת ישראל?",
    answers: ["1948", "1947", "1950", "1945"],
    correctIx: 0,
    difficulty: "easy",
    language: "he",
    category: "history",
  },
  {
    text: "מי הביס את נפוליאון בקרב ווטרלו ב-1815?",
    answers: [
      "הצבא הבריטי והפרוסי",
      "הצבא הרוסי",
      "הצבא האוסטרי",
      "הצבא הספרדי",
    ],
    correctIx: 0,
    difficulty: "easy",
    language: "he",
    category: "history",
  },
  {
    text: "כמה שנים ארכה למעשה 'מלחמת מאה השנים' בין צרפת לאנגליה?",
    answers: ["116", "100", "87", "125"],
    correctIx: 0,
    difficulty: "medium",
    language: "he",
    category: "history",
  },
  {
    text: "מי היה ראש ממשלת בריטניה בשיאה של מלחמת העולם השנייה?",
    answers: [
      "וינסטון צ'רצ'יל",
      "נוויל צ'מברליין",
      "קלמנט אטלי",
      "אנתוני אידן",
    ],
    correctIx: 0,
    difficulty: "medium",
    language: "he",
    category: "history",
  },
  {
    text: "מי היה הקיסר הרומי הראשון?",
    answers: ["אוגוסטוס", "יוליוס קיסר", "קלאודיוס", "קליגולה"],
    correctIx: 0,
    difficulty: "hard",
    language: "he",
    category: "history",
  },
  {
    text: "באיזו שנה נפלה החומה הברלינאית?",
    answers: ["1989", "1991", "1987", "1990"],
    correctIx: 0,
    difficulty: "hard",
    language: "he",
    category: "history",
  },

  // ──────────────────────────────────────────────────────────
  // HE — geography
  // ──────────────────────────────────────────────────────────
  {
    text: "מהי הבירה של אוסטרליה?",
    answers: ["קנברה", "סידני", "מלבורן", "בריסביין"],
    correctIx: 0,
    difficulty: "easy",
    language: "he",
    category: "geography",
  },
  {
    text: "מהו הנהר הארוך ביותר בעולם?",
    answers: ["נילוס", "אמזונס", "מיסיסיפי", "יאנגצה"],
    correctIx: 0,
    difficulty: "easy",
    language: "he",
    category: "geography",
  },
  {
    text: "מהי המדינה הקטנה ביותר בעולם?",
    answers: ["ותיקן", "מונקו", "סן מרינו", "ליכטנשטיין"],
    correctIx: 0,
    difficulty: "medium",
    language: "he",
    category: "geography",
  },
  {
    text: "כמה מדינות חולקות גבול עם ברזיל?",
    answers: ["10", "8", "12", "9"],
    correctIx: 0,
    difficulty: "medium",
    language: "he",
    category: "geography",
  },
  {
    text: "באיזו מדינה נמצאת הפסגה הגבוהה ביותר בדרום אמריקה (אקונקאגואה)?",
    answers: ["ארגנטינה", "צ'ילה", "פרו", "בוליביה"],
    correctIx: 0,
    difficulty: "hard",
    language: "he",
    category: "geography",
  },
  {
    text: "מהו האוקיינוס העמוק ביותר בעולם?",
    answers: ["האוקיינוס השקט", "האוקיינוס ההודי", "האוקיינוס האטלנטי", "הים הקרי"],
    correctIx: 0,
    difficulty: "hard",
    language: "he",
    category: "geography",
  },

  // ──────────────────────────────────────────────────────────
  // HE — israel_local
  // ──────────────────────────────────────────────────────────
  {
    text: "מי היה ראש הממשלה הראשון של מדינת ישראל?",
    answers: ["דוד בן-גוריון", "משה שרת", "לוי אשכול", "גולדה מאיר"],
    correctIx: 0,
    difficulty: "easy",
    language: "he",
    category: "israel_local",
  },
  {
    text: "מהו הנהר הארוך ביותר בישראל?",
    answers: ["הירדן", "הירקון", "הקישון", "הגעתון"],
    correctIx: 0,
    difficulty: "easy",
    language: "he",
    category: "israel_local",
  },
  {
    text: "מתי החלה מלחמת יום הכיפורים?",
    answers: ["אוקטובר 1973", "ספטמבר 1973", "אוקטובר 1967", "יוני 1967"],
    correctIx: 0,
    difficulty: "medium",
    language: "he",
    category: "israel_local",
  },
  {
    text: "כיצד נקרא המבצע שבמסגרתו עלו יהודי אתיופיה לישראל ב-1991?",
    answers: ["מבצע שלמה", "מבצע משה", "מבצע יונתן", "מבצע שושנה"],
    correctIx: 0,
    difficulty: "medium",
    language: "he",
    category: "israel_local",
  },
  {
    text: "כמה חברי כנסת יש בפרלמנט הישראלי?",
    answers: ["120", "100", "150", "110"],
    correctIx: 0,
    difficulty: "hard",
    language: "he",
    category: "israel_local",
  },
  {
    text: "מה היה שם הארגון הצבאי הציוני הראשי שפעל בתקופת המנדט הבריטי?",
    answers: ["ההגנה", "האירגון", "לח\"י", "הפלמ\"ח"],
    correctIx: 0,
    difficulty: "hard",
    language: "he",
    category: "israel_local",
  },

  // ══════════════════════════════════════════════════════════
  // EN — general_knowledge
  // ══════════════════════════════════════════════════════════
  {
    text: "How many sides does a hexagon have?",
    answers: ["6", "5", "7", "8"],
    correctIx: 0,
    difficulty: "easy",
    language: "en",
    category: "general_knowledge",
  },
  {
    text: "What color is produced by mixing red and blue?",
    answers: ["Purple", "Green", "Orange", "Brown"],
    correctIx: 0,
    difficulty: "easy",
    language: "en",
    category: "general_knowledge",
  },
  {
    text: "What is the chemical symbol for gold?",
    answers: ["Au", "Ag", "Go", "Gd"],
    correctIx: 0,
    difficulty: "medium",
    language: "en",
    category: "general_knowledge",
  },
  {
    text: "How many bones are in the adult human body?",
    answers: ["206", "208", "196", "212"],
    correctIx: 0,
    difficulty: "medium",
    language: "en",
    category: "general_knowledge",
  },
  {
    text: "What is the most abundant gas in Earth's atmosphere?",
    answers: ["Nitrogen", "Oxygen", "Carbon Dioxide", "Argon"],
    correctIx: 0,
    difficulty: "hard",
    language: "en",
    category: "general_knowledge",
  },
  {
    text: "In what year did the first moon landing take place?",
    answers: ["1969", "1968", "1972", "1971"],
    correctIx: 0,
    difficulty: "hard",
    language: "en",
    category: "general_knowledge",
  },

  // EN — sports
  {
    text: "How many players are on the court per team in basketball?",
    answers: ["5", "6", "4", "7"],
    correctIx: 0,
    difficulty: "easy",
    language: "en",
    category: "sports",
  },
  {
    text: "How long is a standard marathon race?",
    answers: ["42.195 km", "40 km", "45 km", "26 km"],
    correctIx: 0,
    difficulty: "easy",
    language: "en",
    category: "sports",
  },
  {
    text: "Which country hosted the 2018 FIFA World Cup?",
    answers: ["Russia", "Brazil", "Germany", "Qatar"],
    correctIx: 0,
    difficulty: "medium",
    language: "en",
    category: "sports",
  },
  {
    text: "In what year did Michael Jordan play his last NBA game?",
    answers: ["2003", "2001", "2005", "1999"],
    correctIx: 0,
    difficulty: "medium",
    language: "en",
    category: "sports",
  },
  {
    text: "Who holds the record for most Olympic gold medals overall?",
    answers: ["Michael Phelps", "Usain Bolt", "Carl Lewis", "Mark Spitz"],
    correctIx: 0,
    difficulty: "hard",
    language: "en",
    category: "sports",
  },
  {
    text: "In what year were the first modern Olympic Games held?",
    answers: ["1896", "1900", "1892", "1904"],
    correctIx: 0,
    difficulty: "hard",
    language: "en",
    category: "sports",
  },

  // EN — movies_tv
  {
    text: "Who played Iron Man in the Marvel Cinematic Universe?",
    answers: ["Robert Downey Jr.", "Chris Evans", "Mark Ruffalo", "Chris Hemsworth"],
    correctIx: 0,
    difficulty: "easy",
    language: "en",
    category: "movies_tv",
  },
  {
    text: "What animated movie features the song 'Let It Go'?",
    answers: ["Frozen", "Tangled", "Brave", "Moana"],
    correctIx: 0,
    difficulty: "easy",
    language: "en",
    category: "movies_tv",
  },
  {
    text: "Who directed 'Pulp Fiction' (1994)?",
    answers: ["Quentin Tarantino", "Martin Scorsese", "David Fincher", "Ridley Scott"],
    correctIx: 0,
    difficulty: "medium",
    language: "en",
    category: "movies_tv",
  },
  {
    text: "In what year was 'The Godfather' released?",
    answers: ["1972", "1974", "1970", "1968"],
    correctIx: 0,
    difficulty: "medium",
    language: "en",
    category: "movies_tv",
  },
  {
    text: "Which film won the very first Academy Award for Best Picture?",
    answers: ["Wings", "Sunrise", "The Jazz Singer", "Seventh Heaven"],
    correctIx: 0,
    difficulty: "hard",
    language: "en",
    category: "movies_tv",
  },
  {
    text: "Who composed the score for 'Schindler's List'?",
    answers: ["John Williams", "Hans Zimmer", "Ennio Morricone", "Howard Shore"],
    correctIx: 0,
    difficulty: "hard",
    language: "en",
    category: "movies_tv",
  },

  // EN — music
  {
    text: "How many strings does a standard acoustic guitar have?",
    answers: ["6", "4", "7", "8"],
    correctIx: 0,
    difficulty: "easy",
    language: "en",
    category: "music",
  },
  {
    text: "What is the highest female singing voice?",
    answers: ["Soprano", "Mezzo-soprano", "Alto", "Contralto"],
    correctIx: 0,
    difficulty: "easy",
    language: "en",
    category: "music",
  },
  {
    text: "In which city did The Beatles form?",
    answers: ["Liverpool", "London", "Manchester", "Birmingham"],
    correctIx: 0,
    difficulty: "medium",
    language: "en",
    category: "music",
  },
  {
    text: "Who composed 'The Four Seasons'?",
    answers: ["Vivaldi", "Bach", "Handel", "Telemann"],
    correctIx: 0,
    difficulty: "medium",
    language: "en",
    category: "music",
  },
  {
    text: "How many symphonies did Ludwig van Beethoven compose?",
    answers: ["9", "7", "11", "6"],
    correctIx: 0,
    difficulty: "hard",
    language: "en",
    category: "music",
  },
  {
    text: "Which band released the album 'Dark Side of the Moon' in 1973?",
    answers: ["Pink Floyd", "Led Zeppelin", "The Rolling Stones", "The Who"],
    correctIx: 0,
    difficulty: "hard",
    language: "en",
    category: "music",
  },

  // EN — science_tech
  {
    text: "What planet is known as the Red Planet?",
    answers: ["Mars", "Venus", "Jupiter", "Saturn"],
    correctIx: 0,
    difficulty: "easy",
    language: "en",
    category: "science_tech",
  },
  {
    text: "What is the hardest natural substance?",
    answers: ["Diamond", "Quartz", "Topaz", "Corundum"],
    correctIx: 0,
    difficulty: "easy",
    language: "en",
    category: "science_tech",
  },
  {
    text: "What does DNA stand for?",
    answers: [
      "Deoxyribonucleic acid",
      "Dinitrogen acid",
      "Deoxyribose nucleotide",
      "Dynamic nucleic acid",
    ],
    correctIx: 0,
    difficulty: "medium",
    language: "en",
    category: "science_tech",
  },
  {
    text: "How many elements are in the periodic table as of 2024?",
    answers: ["118", "112", "120", "116"],
    correctIx: 0,
    difficulty: "medium",
    language: "en",
    category: "science_tech",
  },
  {
    text: "What particle has no mass and travels at the speed of light?",
    answers: ["Photon", "Electron", "Neutron", "Neutrino"],
    correctIx: 0,
    difficulty: "hard",
    language: "en",
    category: "science_tech",
  },
  {
    text: "What is the approximate temperature at the core of the Sun?",
    answers: ["15 million °C", "5,500 °C", "1 million °C", "100 million °C"],
    correctIx: 0,
    difficulty: "hard",
    language: "en",
    category: "science_tech",
  },

  // EN — history
  {
    text: "Who was the first President of the United States?",
    answers: ["George Washington", "John Adams", "Thomas Jefferson", "Benjamin Franklin"],
    correctIx: 0,
    difficulty: "easy",
    language: "en",
    category: "history",
  },
  {
    text: "In what year did World War II end?",
    answers: ["1945", "1944", "1946", "1943"],
    correctIx: 0,
    difficulty: "easy",
    language: "en",
    category: "history",
  },
  {
    text: "What empire was built by Genghis Khan?",
    answers: ["Mongol Empire", "Ottoman Empire", "Byzantine Empire", "Persian Empire"],
    correctIx: 0,
    difficulty: "medium",
    language: "en",
    category: "history",
  },
  {
    text: "Who was the first woman to win a Nobel Prize?",
    answers: ["Marie Curie", "Rosalind Franklin", "Lise Meitner", "Dorothy Hodgkin"],
    correctIx: 0,
    difficulty: "medium",
    language: "en",
    category: "history",
  },
  {
    text: "In what year did the French Revolution begin?",
    answers: ["1789", "1776", "1793", "1799"],
    correctIx: 0,
    difficulty: "hard",
    language: "en",
    category: "history",
  },
  {
    text: "Who was the last ruling pharaoh of ancient Egypt?",
    answers: ["Cleopatra VII", "Nefertiti", "Hatshepsut", "Ramesses II"],
    correctIx: 0,
    difficulty: "hard",
    language: "en",
    category: "history",
  },

  // EN — geography
  {
    text: "What is the capital city of France?",
    answers: ["Paris", "Lyon", "Marseille", "Bordeaux"],
    correctIx: 0,
    difficulty: "easy",
    language: "en",
    category: "geography",
  },
  {
    text: "What is the longest river in the world?",
    answers: ["Nile", "Amazon", "Mississippi", "Yangtze"],
    correctIx: 0,
    difficulty: "easy",
    language: "en",
    category: "geography",
  },
  {
    text: "Which country has the most natural lakes?",
    answers: ["Canada", "Russia", "United States", "Finland"],
    correctIx: 0,
    difficulty: "medium",
    language: "en",
    category: "geography",
  },
  {
    text: "What is the smallest continent by land area?",
    answers: ["Australia", "Europe", "Antarctica", "South America"],
    correctIx: 0,
    difficulty: "medium",
    language: "en",
    category: "geography",
  },
  {
    text: "What is the name of the deepest lake in the world?",
    answers: ["Lake Baikal", "Lake Tanganyika", "Caspian Sea", "Lake Superior"],
    correctIx: 0,
    difficulty: "hard",
    language: "en",
    category: "geography",
  },
  {
    text: "In which mountain range is Mount Everest located?",
    answers: ["Himalayas", "Karakoram", "Hindu Kush", "Pamir"],
    correctIx: 0,
    difficulty: "hard",
    language: "en",
    category: "geography",
  },

  // EN — israel_local
  {
    text: "What is the capital of Israel?",
    answers: ["Jerusalem", "Tel Aviv", "Haifa", "Beer Sheva"],
    correctIx: 0,
    difficulty: "easy",
    language: "en",
    category: "israel_local",
  },
  {
    text: "What language is primarily spoken in Israel?",
    answers: ["Hebrew", "Arabic", "Yiddish", "Aramaic"],
    correctIx: 0,
    difficulty: "easy",
    language: "en",
    category: "israel_local",
  },
  {
    text: "What is the name of Israel's national airline?",
    answers: ["El Al", "Arkia", "Israir", "Flydubai"],
    correctIx: 0,
    difficulty: "medium",
    language: "en",
    category: "israel_local",
  },
  {
    text: "In what year did Israel win the Eurovision Song Contest for the first time?",
    answers: ["1978", "1982", "1973", "1986"],
    correctIx: 0,
    difficulty: "medium",
    language: "en",
    category: "israel_local",
  },
  {
    text: "What is the name of the ancient fortress where Jewish rebels made their last stand in 73 CE?",
    answers: ["Masada", "Gamla", "Herodion", "Antonia"],
    correctIx: 0,
    difficulty: "hard",
    language: "en",
    category: "israel_local",
  },
  {
    text: "What sea borders Israel to the west?",
    answers: ["Mediterranean Sea", "Red Sea", "Dead Sea", "Sea of Galilee"],
    correctIx: 0,
    difficulty: "hard",
    language: "en",
    category: "israel_local",
  },

  // ══════════════════════════════════════════════════════════
  // ADDITIONS — 3 per cell (144 total)
  // ══════════════════════════════════════════════════════════

  // ── HE — general_knowledge ──
  {
    text: "כמה צבעים יש בקשת בענן?",
    answers: ["5", "7", "6", "8"],
    correctIx: 1,
    difficulty: "easy",
    language: "he",
    category: "general_knowledge",
  },
  {
    text: "מהי צורתו של עיגול?",
    answers: ["מרובע", "משולש", "עגול", "מלבני"],
    correctIx: 2,
    difficulty: "easy",
    language: "he",
    category: "general_knowledge",
  },
  {
    text: "כמה שעות יש ביממה?",
    answers: ["24", "12", "36", "48"],
    correctIx: 0,
    difficulty: "easy",
    language: "he",
    category: "general_knowledge",
  },
  {
    text: "מהי יחידת המדידה של עוצמת רעידות אדמה?",
    answers: ["צלזיוס", "ריכטר", "פסקל", "ניוטון"],
    correctIx: 1,
    difficulty: "medium",
    language: "he",
    category: "general_knowledge",
  },
  {
    text: "כמה זוויות יש במחומש?",
    answers: ["4", "6", "5", "7"],
    correctIx: 2,
    difficulty: "medium",
    language: "he",
    category: "general_knowledge",
  },
  {
    text: "מהי המטבע הרשמית של יפן?",
    answers: ["יואן", "וון", "באט", "יֵן"],
    correctIx: 3,
    difficulty: "medium",
    language: "he",
    category: "general_knowledge",
  },
  {
    text: "מהו היסוד הכימי עם המספר האטומי 1?",
    answers: ["מימן", "הליום", "חמצן", "פחמן"],
    correctIx: 0,
    difficulty: "hard",
    language: "he",
    category: "general_knowledge",
  },
  {
    text: "מי המציא את נורת הליבון המסחרית המוצלחת הראשונה?",
    answers: ["ניקולה טסלה", "תומס אדיסון", "אלכסנדר בל", "מייקל פאראדיי"],
    correctIx: 1,
    difficulty: "hard",
    language: "he",
    category: "general_knowledge",
  },
  {
    text: "כמה זוויות מעלות יש בסכום זוויותיו של משולש?",
    answers: ["360", "90", "270", "180"],
    correctIx: 3,
    difficulty: "hard",
    language: "he",
    category: "general_knowledge",
  },

  // ── HE — sports ──
  {
    text: "כמה נקודות מקבלים על סל רגיל בכדורסל (לא מעבר לקו השלוש)?",
    answers: ["3", "2", "1", "4"],
    correctIx: 1,
    difficulty: "easy",
    language: "he",
    category: "sports",
  },
  {
    text: "באיזה ספורט משתמשים ברקטה ובכדור צהוב פלומתי?",
    answers: ["טניס", "כדורעף", "באולינג", "הוקי"],
    correctIx: 0,
    difficulty: "easy",
    language: "he",
    category: "sports",
  },
  {
    text: "כמה שחקנים יש בקבוצת כדורעף על המגרש בו-זמנית?",
    answers: ["5", "7", "6", "8"],
    correctIx: 2,
    difficulty: "easy",
    language: "he",
    category: "sports",
  },
  {
    text: "כל כמה שנים מתקיים מונדיאל הכדורגל?",
    answers: ["שנתיים", "ארבע שנים", "שלוש שנים", "חמש שנים"],
    correctIx: 1,
    difficulty: "medium",
    language: "he",
    category: "sports",
  },
  {
    text: "באיזו מדינה נולד הכדורגלן ליאו מסי?",
    answers: ["ארגנטינה", "ברזיל", "אורוגוואי", "ספרד"],
    correctIx: 0,
    difficulty: "medium",
    language: "he",
    category: "sports",
  },
  {
    text: "כמה גבינות (מסלולים) יש במגרש בולינג סטנדרטי בפריים אחד לשחקן?",
    answers: ["12 כדורים", "10 פינים", "9 פינים", "11 פינים"],
    correctIx: 1,
    difficulty: "medium",
    language: "he",
    category: "sports",
  },
  {
    text: "מי זכה בכדור הזהב הראשון בהיסטוריה (1956)?",
    answers: ["סטנלי מתיוס", "אלפרדו די-סטפנו", "פושקש", "ריימון קופה"],
    correctIx: 0,
    difficulty: "hard",
    language: "he",
    category: "sports",
  },
  {
    text: "כמה אליפויות עולם בפורמולה 1 כבש מיכאל שומאכר?",
    answers: ["5", "6", "7", "8"],
    correctIx: 2,
    difficulty: "hard",
    language: "he",
    category: "sports",
  },
  {
    text: "באיזו שנה זכתה מכבי תל אביב באליפות אירופה בכדורסל בפעם הראשונה?",
    answers: ["1981", "1977", "1985", "1979"],
    correctIx: 1,
    difficulty: "hard",
    language: "he",
    category: "sports",
  },

  // ── HE — movies_tv ──
  {
    text: "איזו חברה הפיקה את הסרט 'מלך האריות' (1994)?",
    answers: ["פיקסאר", "דרימוורקס", "דיסני", "וורנר ברוס"],
    correctIx: 2,
    difficulty: "easy",
    language: "he",
    category: "movies_tv",
  },
  {
    text: "מי משחק את הדמות הראשית בסדרת סרטי 'מטריקס'?",
    answers: ["טום קרוז", "קיאנו ריבס", "ויל סמית'", "מאט דיימון"],
    correctIx: 1,
    difficulty: "easy",
    language: "he",
    category: "movies_tv",
  },
  {
    text: "באיזה סרט מצויר מופיעה הדמות וודי, צעצוע בובת בוקר?",
    answers: ["צעצוע של סיפור", "שרק", "נמו", "קארס"],
    correctIx: 0,
    difficulty: "easy",
    language: "he",
    category: "movies_tv",
  },
  {
    text: "מי ביים את הסרט 'התחלה' (Inception)?",
    answers: ["כריסטופר נולאן", "ג'יימס קמרון", "סטיבן ספילברג", "דניס וילנב"],
    correctIx: 0,
    difficulty: "medium",
    language: "he",
    category: "movies_tv",
  },
  {
    text: "מהי הסדרה שבה מופיעה הדמות וולטר וייט, מורה לכימיה?",
    answers: ["מד מן", "הסופרנוס", "שובר שורות", "מתים מהלכים"],
    correctIx: 2,
    difficulty: "medium",
    language: "he",
    category: "movies_tv",
  },
  {
    text: "כמה פרסי אוסקר זכה הסרט 'טיטאניק' (1997)?",
    answers: ["9", "11", "7", "13"],
    correctIx: 1,
    difficulty: "medium",
    language: "he",
    category: "movies_tv",
  },
  {
    text: "מי כתבה את ספרי 'הארי פוטר' שעובדו לסרטים?",
    answers: ["סוזן קולינס", "סטפני מאייר", "ג'.ק. רולינג", "ג'.ר.ר. טולקין"],
    correctIx: 2,
    difficulty: "hard",
    language: "he",
    category: "movies_tv",
  },
  {
    text: "באיזו שנה שודרה הפרק הראשון של הסדרה 'הסימפסונים' כסדרה עצמאית?",
    answers: ["1989", "1991", "1987", "1993"],
    correctIx: 0,
    difficulty: "hard",
    language: "he",
    category: "movies_tv",
  },
  {
    text: "מי זכה באוסקר השחקן הטוב ביותר על תפקידו ב'מלקולם איקס'? (שאלת היכר: לא זכה) — מי זכה על 'פילדלפיה' (1993)?",
    answers: ["טום הנקס", "דנזל וושינגטון", "אל פצ'ינו", "אנתוני הופקינס"],
    correctIx: 0,
    difficulty: "hard",
    language: "he",
    category: "movies_tv",
  },

  // ── HE — music ──
  {
    text: "כמה מיתרים יש בכינור?",
    answers: ["4", "6", "5", "3"],
    correctIx: 0,
    difficulty: "easy",
    language: "he",
    category: "music",
  },
  {
    text: "איזה כלי נגינה מנגנים בעזרת קשת ומחזיקים בין הברכיים?",
    answers: ["כינור", "צ'לו", "חליל", "חצוצרה"],
    correctIx: 1,
    difficulty: "easy",
    language: "he",
    category: "music",
  },
  {
    text: "מהו הכלי בעל הקלידים השחורים והלבנים?",
    answers: ["גיטרה", "תופים", "פסנתר", "סקסופון"],
    correctIx: 2,
    difficulty: "easy",
    language: "he",
    category: "music",
  },
  {
    text: "מי הזמרת שביצעה את השיר 'Rolling in the Deep'?",
    answers: ["אדל", "ביונסה", "רינה", "טיילור סוויפט"],
    correctIx: 0,
    difficulty: "medium",
    language: "he",
    category: "music",
  },
  {
    text: "מאיזו מדינה הגיעה להקת 'ABBA'?",
    answers: ["נורבגיה", "שבדיה", "דנמרק", "פינלנד"],
    correctIx: 1,
    difficulty: "medium",
    language: "he",
    category: "music",
  },
  {
    text: "כמה תווים יש בסולם דיאטוני מז'ורי שלם (לפני חזרה על האוקטבה)?",
    answers: ["8", "5", "7", "12"],
    correctIx: 2,
    difficulty: "medium",
    language: "he",
    category: "music",
  },
  {
    text: "מי הלחין את האופרה 'חליל הקסם'?",
    answers: ["וגנר", "ורדי", "פוצ'יני", "מוצרט"],
    correctIx: 3,
    difficulty: "hard",
    language: "he",
    category: "music",
  },
  {
    text: "באיזו שנה נפטר אלביס פרסלי?",
    answers: ["1977", "1980", "1975", "1979"],
    correctIx: 0,
    difficulty: "hard",
    language: "he",
    category: "music",
  },
  {
    text: "מהו שמה האמיתי של הזמרת ליידי גאגא?",
    answers: ["סטפני ג'רמנוטה", "רובין פנטי", "אלסיה מור", "קייטי הדסון"],
    correctIx: 0,
    difficulty: "hard",
    language: "he",
    category: "music",
  },

  // ── HE — science_tech ──
  {
    text: "איזה איבר בגוף האדם שואב דם?",
    answers: ["הכבד", "הלב", "הריאות", "הכליות"],
    correctIx: 1,
    difficulty: "easy",
    language: "he",
    category: "science_tech",
  },
  {
    text: "מהו הגז שאנו נושמים ונחוץ לחיינו?",
    answers: ["חנקן", "פחמן דו-חמצני", "חמצן", "מימן"],
    correctIx: 2,
    difficulty: "easy",
    language: "he",
    category: "science_tech",
  },
  {
    text: "מהו מצב הצבירה של מים בטמפרטורה מתחת לאפס מעלות?",
    answers: ["נוזל", "גז", "אדים", "מוצק (קרח)"],
    correctIx: 3,
    difficulty: "easy",
    language: "he",
    category: "science_tech",
  },
  {
    text: "כמה רגליים יש לחרק בוגר?",
    answers: ["6", "8", "4", "10"],
    correctIx: 0,
    difficulty: "medium",
    language: "he",
    category: "science_tech",
  },
  {
    text: "מהו האיבר הגדול ביותר בגוף האדם?",
    answers: ["הכבד", "העור", "המעי", "הריאות"],
    correctIx: 1,
    difficulty: "medium",
    language: "he",
    category: "science_tech",
  },
  {
    text: "מהי יחידת המדידה הבסיסית של זרם חשמלי?",
    answers: ["וולט", "ואט", "אמפר", "אוהם"],
    correctIx: 2,
    difficulty: "medium",
    language: "he",
    category: "science_tech",
  },
  {
    text: "מהו שמו של החלקיק התת-אטומי בעל מטען חשמלי חיובי בגרעין?",
    answers: ["אלקטרון", "נייטרון", "פוטון", "פרוטון"],
    correctIx: 3,
    difficulty: "hard",
    language: "he",
    category: "science_tech",
  },
  {
    text: "מי ניסח את תורת היחסות הכללית?",
    answers: ["אלברט איינשטיין", "אייזק ניוטון", "נילס בוהר", "מקס פלאנק"],
    correctIx: 0,
    difficulty: "hard",
    language: "he",
    category: "science_tech",
  },
  {
    text: "מהי הטמפרטורה של האפס המוחלט בצלזיוס (בקירוב)?",
    answers: ["0°C", "-273°C", "-100°C", "-459°C"],
    correctIx: 1,
    difficulty: "hard",
    language: "he",
    category: "science_tech",
  },

  // ── HE — history ──
  {
    text: "באיזו יבשת ממוקמות הפירמידות של גיזה?",
    answers: ["אסיה", "אירופה", "אפריקה", "אמריקה"],
    correctIx: 2,
    difficulty: "easy",
    language: "he",
    category: "history",
  },
  {
    text: "מי גילה את אמריקה עבור הכתר הספרדי ב-1492?",
    answers: ["כריסטופר קולומבוס", "ואסקו דה גאמה", "מגלן", "אמריגו וספוצ'י"],
    correctIx: 0,
    difficulty: "easy",
    language: "he",
    category: "history",
  },
  {
    text: "באיזו מדינה החלה מלחמת העולם השנייה בעקבות הפלישה ב-1939?",
    answers: ["צרפת", "פולין", "בלגיה", "צ'כיה"],
    correctIx: 1,
    difficulty: "easy",
    language: "he",
    category: "history",
  },
  {
    text: "מי הייתה מנהיגת התנועה לזכויות ההצבעה שהובילה את הצעדה לסל­מה? (שאלה: מי הוביל את צעדת המלח בהודו?)",
    answers: ["נהרו", "מהטמה גנדי", "צ'רצ'יל", "מנדלה"],
    correctIx: 1,
    difficulty: "medium",
    language: "he",
    category: "history",
  },
  {
    text: "איזו ציביליזציה בנתה את מאצ'ו פיצ'ו בפרו?",
    answers: ["האצטקים", "המאיה", "האינקה", "האולמקים"],
    correctIx: 2,
    difficulty: "medium",
    language: "he",
    category: "history",
  },
  {
    text: "באיזו שנה הוטלה פצצת האטום הראשונה על הירושימה?",
    answers: ["1943", "1944", "1946", "1945"],
    correctIx: 3,
    difficulty: "medium",
    language: "he",
    category: "history",
  },
  {
    text: "מי היה הצאר הרוסי שכונה 'הגדול' ויסד את סנט פטרבורג?",
    answers: ["פטר הגדול", "איוואן האיום", "ניקולאי השני", "אלכסנדר השני"],
    correctIx: 0,
    difficulty: "hard",
    language: "he",
    category: "history",
  },
  {
    text: "באיזו שנה חתמו על מגנה כרטה באנגליה?",
    answers: ["1066", "1215", "1348", "1485"],
    correctIx: 1,
    difficulty: "hard",
    language: "he",
    category: "history",
  },
  {
    text: "מי הייתה המלכה שמלכה על בריטניה במשך התקופה הארוכה ביותר עד 2015 (לפני אליזבת השנייה)?",
    answers: ["מרי הראשונה", "אן", "ויקטוריה", "אליזבת הראשונה"],
    correctIx: 2,
    difficulty: "hard",
    language: "he",
    category: "history",
  },

  // ── HE — geography ──
  {
    text: "מהי הבירה של צרפת?",
    answers: ["פריז", "ליון", "ניס", "מרסיי"],
    correctIx: 0,
    difficulty: "easy",
    language: "he",
    category: "geography",
  },
  {
    text: "באיזו יבשת נמצאת מצרים ברובה?",
    answers: ["אסיה", "אפריקה", "אירופה", "אוקיאניה"],
    correctIx: 1,
    difficulty: "easy",
    language: "he",
    category: "geography",
  },
  {
    text: "מהו הים הגדול ביותר התחום ביבשה כמעט לחלוטין?",
    answers: ["הים האדום", "הים השחור", "הים התיכון", "הים הבלטי"],
    correctIx: 2,
    difficulty: "easy",
    language: "he",
    category: "geography",
  },
  {
    text: "מהי הבירה של קנדה?",
    answers: ["טורונטו", "ונקובר", "מונטריאול", "אוטווה"],
    correctIx: 3,
    difficulty: "medium",
    language: "he",
    category: "geography",
  },
  {
    text: "מהי המדינה הגדולה ביותר בעולם מבחינת שטח?",
    answers: ["רוסיה", "קנדה", "סין", "ארה\"ב"],
    correctIx: 0,
    difficulty: "medium",
    language: "he",
    category: "geography",
  },
  {
    text: "מהו המדבר הגדול ביותר בעולם (מדבר חם)?",
    answers: ["גובי", "סהרה", "כלהארי", "אטקמה"],
    correctIx: 1,
    difficulty: "medium",
    language: "he",
    category: "geography",
  },
  {
    text: "באיזו מדינה נמצאת העיר טימבוקטו?",
    answers: ["ניז'ר", "אלג'יריה", "מאלי", "ניגריה"],
    correctIx: 2,
    difficulty: "hard",
    language: "he",
    category: "geography",
  },
  {
    text: "מהי הבירה של אוסטרליה הקודמת לקנברה שכמעט נבחרה (השאלה: מהי בירת ניו זילנד)?",
    answers: ["אוקלנד", "כרייסטצ'רץ'", "המילטון", "וולינגטון"],
    correctIx: 3,
    difficulty: "hard",
    language: "he",
    category: "geography",
  },
  {
    text: "כמה אזורי זמן חוצים את רוסיה?",
    answers: ["11", "7", "9", "5"],
    correctIx: 0,
    difficulty: "hard",
    language: "he",
    category: "geography",
  },

  // ── HE — israel_local ──
  {
    text: "מהי העיר הגדולה ביותר בישראל מבחינת אוכלוסייה?",
    answers: ["תל אביב", "ירושלים", "חיפה", "ראשון לציון"],
    correctIx: 1,
    difficulty: "easy",
    language: "he",
    category: "israel_local",
  },
  {
    text: "מהו הים שנמצא בנקודה הנמוכה ביותר על פני כדור הארץ?",
    answers: ["ים סוף", "הכנרת", "הים התיכון", "ים המלח"],
    correctIx: 3,
    difficulty: "easy",
    language: "he",
    category: "israel_local",
  },
  {
    text: "מהו המטבע הרשמי של מדינת ישראל?",
    answers: ["שקל חדש", "לירה", "דולר", "אגורה"],
    correctIx: 0,
    difficulty: "easy",
    language: "he",
    category: "israel_local",
  },
  {
    text: "באיזו עיר נמצא מוזיאון 'יד ושם'?",
    answers: ["תל אביב", "ירושלים", "חיפה", "באר שבע"],
    correctIx: 1,
    difficulty: "medium",
    language: "he",
    category: "israel_local",
  },
  {
    text: "מי הייתה ראש הממשלה האישה היחידה בתולדות ישראל?",
    answers: ["שולמית אלוני", "גולדה מאיר", "ציפי לבני", "דורית בייניש"],
    correctIx: 1,
    difficulty: "medium",
    language: "he",
    category: "israel_local",
  },
  {
    text: "מהו ההר הגבוה ביותר בישראל (בשטחה הריבוני)?",
    answers: ["הר מירון", "הר תבור", "הר רמון", "הר כנען"],
    correctIx: 0,
    difficulty: "medium",
    language: "he",
    category: "israel_local",
  },
  {
    text: "באיזו שנה נחתם הסכם השלום בין ישראל למצרים?",
    answers: ["1977", "1981", "1979", "1982"],
    correctIx: 2,
    difficulty: "hard",
    language: "he",
    category: "israel_local",
  },
  {
    text: "מי היה נשיא המדינה הראשון של ישראל?",
    answers: ["יצחק בן-צבי", "זלמן שזר", "חיים ויצמן", "אפרים קציר"],
    correctIx: 2,
    difficulty: "hard",
    language: "he",
    category: "israel_local",
  },
  {
    text: "מהו שמו של חבל הארץ הצפוני ביותר בישראל הכולל את קריית שמונה ומטולה?",
    answers: ["הגליל העליון", "העמקים", "הגולן", "השרון"],
    correctIx: 0,
    difficulty: "hard",
    language: "he",
    category: "israel_local",
  },

  // ── EN — general_knowledge ──
  {
    text: "How many days are there in a week?",
    answers: ["5", "7", "6", "8"],
    correctIx: 1,
    difficulty: "easy",
    language: "en",
    category: "general_knowledge",
  },
  {
    text: "What is the freezing point of water in Celsius?",
    answers: ["32°", "10°", "0°", "-10°"],
    correctIx: 2,
    difficulty: "easy",
    language: "en",
    category: "general_knowledge",
  },
  {
    text: "How many continents are there on Earth?",
    answers: ["7", "5", "6", "8"],
    correctIx: 0,
    difficulty: "easy",
    language: "en",
    category: "general_knowledge",
  },
  {
    text: "What is the largest planet in our solar system?",
    answers: ["Saturn", "Jupiter", "Neptune", "Earth"],
    correctIx: 1,
    difficulty: "medium",
    language: "en",
    category: "general_knowledge",
  },
  {
    text: "What is the official currency of the United Kingdom?",
    answers: ["Euro", "Dollar", "Pound Sterling", "Franc"],
    correctIx: 2,
    difficulty: "medium",
    language: "en",
    category: "general_knowledge",
  },
  {
    text: "How many degrees are in a right angle?",
    answers: ["45", "180", "360", "90"],
    correctIx: 3,
    difficulty: "medium",
    language: "en",
    category: "general_knowledge",
  },
  {
    text: "What is the chemical symbol for sodium?",
    answers: ["Na", "So", "Sd", "Sn"],
    correctIx: 0,
    difficulty: "hard",
    language: "en",
    category: "general_knowledge",
  },
  {
    text: "Which Greek letter is commonly used to represent the ratio of a circle's circumference to its diameter?",
    answers: ["Sigma", "Pi", "Theta", "Delta"],
    correctIx: 1,
    difficulty: "hard",
    language: "en",
    category: "general_knowledge",
  },
  {
    text: "In Roman numerals, what number does the letter 'C' represent?",
    answers: ["50", "500", "100", "1000"],
    correctIx: 2,
    difficulty: "hard",
    language: "en",
    category: "general_knowledge",
  },

  // ── EN — sports ──
  {
    text: "In which sport would you perform a slam dunk?",
    answers: ["Tennis", "Basketball", "Golf", "Cricket"],
    correctIx: 1,
    difficulty: "easy",
    language: "en",
    category: "sports",
  },
  {
    text: "How many holes are played in a standard round of golf?",
    answers: ["9", "12", "18", "24"],
    correctIx: 2,
    difficulty: "easy",
    language: "en",
    category: "sports",
  },
  {
    text: "What color card does a football referee show for a serious foul resulting in ejection?",
    answers: ["Red", "Yellow", "Green", "Blue"],
    correctIx: 0,
    difficulty: "easy",
    language: "en",
    category: "sports",
  },
  {
    text: "Which country has won the most FIFA World Cup titles?",
    answers: ["Germany", "Brazil", "Italy", "Argentina"],
    correctIx: 1,
    difficulty: "medium",
    language: "en",
    category: "sports",
  },
  {
    text: "In tennis, what is the term for a score of zero?",
    answers: ["Nil", "Duck", "Love", "Bagel"],
    correctIx: 2,
    difficulty: "medium",
    language: "en",
    category: "sports",
  },
  {
    text: "How many Grand Slam tournaments are there in tennis each year?",
    answers: ["3", "5", "6", "4"],
    correctIx: 3,
    difficulty: "medium",
    language: "en",
    category: "sports",
  },
  {
    text: "Who is the all-time leading scorer in NBA regular-season history (as of 2024)?",
    answers: ["LeBron James", "Kareem Abdul-Jabbar", "Karl Malone", "Michael Jordan"],
    correctIx: 0,
    difficulty: "hard",
    language: "en",
    category: "sports",
  },
  {
    text: "In which year did Roger Bannister first run a mile in under four minutes?",
    answers: ["1948", "1954", "1960", "1952"],
    correctIx: 1,
    difficulty: "hard",
    language: "en",
    category: "sports",
  },
  {
    text: "What is the maximum break possible in a single frame of snooker?",
    answers: ["155", "180", "147", "120"],
    correctIx: 2,
    difficulty: "hard",
    language: "en",
    category: "sports",
  },

  // ── EN — movies_tv ──
  {
    text: "Which movie features a character named Forrest Gump?",
    answers: ["Forrest Gump", "Cast Away", "Big", "Philadelphia"],
    correctIx: 0,
    difficulty: "easy",
    language: "en",
    category: "movies_tv",
  },
  {
    text: "What is the name of the wizard school in Harry Potter?",
    answers: ["Durmstrang", "Hogwarts", "Beauxbatons", "Ilvermorny"],
    correctIx: 1,
    difficulty: "easy",
    language: "en",
    category: "movies_tv",
  },
  {
    text: "Which superhero is known as the 'Caped Crusader'?",
    answers: ["Superman", "Spider-Man", "Batman", "Iron Man"],
    correctIx: 2,
    difficulty: "easy",
    language: "en",
    category: "movies_tv",
  },
  {
    text: "Who directed the 1975 thriller 'Jaws'?",
    answers: ["Steven Spielberg", "George Lucas", "Francis Ford Coppola", "Brian De Palma"],
    correctIx: 0,
    difficulty: "medium",
    language: "en",
    category: "movies_tv",
  },
  {
    text: "In the TV series 'Friends', what is the name of Ross's pet monkey?",
    answers: ["Mr. Bigglesworth", "Marcel", "Crystal", "Bubbles"],
    correctIx: 1,
    difficulty: "medium",
    language: "en",
    category: "movies_tv",
  },
  {
    text: "Which actress played Hermione Granger in the Harry Potter films?",
    answers: ["Evanna Lynch", "Bonnie Wright", "Emma Watson", "Emma Stone"],
    correctIx: 2,
    difficulty: "medium",
    language: "en",
    category: "movies_tv",
  },
  {
    text: "Who directed the science-fiction epic 'Blade Runner' (1982)?",
    answers: ["James Cameron", "George Lucas", "Stanley Kubrick", "Ridley Scott"],
    correctIx: 3,
    difficulty: "hard",
    language: "en",
    category: "movies_tv",
  },
  {
    text: "Which 1941 film by Orson Welles is frequently cited as the greatest film ever made?",
    answers: ["Citizen Kane", "Casablanca", "Gone with the Wind", "Vertigo"],
    correctIx: 0,
    difficulty: "hard",
    language: "en",
    category: "movies_tv",
  },
  {
    text: "Which actor has won the most Academy Awards for acting (a record three for lead actor)?",
    answers: ["Jack Nicholson", "Daniel Day-Lewis", "Marlon Brando", "Tom Hanks"],
    correctIx: 1,
    difficulty: "hard",
    language: "en",
    category: "movies_tv",
  },

  // ── EN — music ──
  {
    text: "Which instrument has 88 keys?",
    answers: ["Piano", "Organ", "Harp", "Accordion"],
    correctIx: 0,
    difficulty: "easy",
    language: "en",
    category: "music",
  },
  {
    text: "What is the lowest male singing voice?",
    answers: ["Tenor", "Bass", "Baritone", "Countertenor"],
    correctIx: 1,
    difficulty: "easy",
    language: "en",
    category: "music",
  },
  {
    text: "Which of these is a percussion instrument?",
    answers: ["Flute", "Violin", "Drums", "Trumpet"],
    correctIx: 2,
    difficulty: "easy",
    language: "en",
    category: "music",
  },
  {
    text: "Which artist is known as the 'King of Pop'?",
    answers: ["Elvis Presley", "Michael Jackson", "Prince", "Justin Timberlake"],
    correctIx: 1,
    difficulty: "medium",
    language: "en",
    category: "music",
  },
  {
    text: "How many lines are there in a standard musical staff?",
    answers: ["4", "6", "5", "7"],
    correctIx: 2,
    difficulty: "medium",
    language: "en",
    category: "music",
  },
  {
    text: "Which country did the band U2 originate from?",
    answers: ["England", "Scotland", "United States", "Ireland"],
    correctIx: 3,
    difficulty: "medium",
    language: "en",
    category: "music",
  },
  {
    text: "Who composed the opera 'The Marriage of Figaro'?",
    answers: ["Mozart", "Verdi", "Wagner", "Rossini"],
    correctIx: 0,
    difficulty: "hard",
    language: "en",
    category: "music",
  },
  {
    text: "Which musical term means to play gradually louder?",
    answers: ["Diminuendo", "Crescendo", "Staccato", "Legato"],
    correctIx: 1,
    difficulty: "hard",
    language: "en",
    category: "music",
  },
  {
    text: "In which year was Wolfgang Amadeus Mozart born?",
    answers: ["1732", "1770", "1756", "1749"],
    correctIx: 2,
    difficulty: "hard",
    language: "en",
    category: "music",
  },

  // ── EN — science_tech ──
  {
    text: "Which gas do plants absorb from the atmosphere for photosynthesis?",
    answers: ["Carbon dioxide", "Oxygen", "Nitrogen", "Hydrogen"],
    correctIx: 0,
    difficulty: "easy",
    language: "en",
    category: "science_tech",
  },
  {
    text: "What organ is responsible for pumping blood in the human body?",
    answers: ["Lungs", "Heart", "Liver", "Kidney"],
    correctIx: 1,
    difficulty: "easy",
    language: "en",
    category: "science_tech",
  },
  {
    text: "How many legs does a spider have?",
    answers: ["6", "10", "8", "12"],
    correctIx: 2,
    difficulty: "easy",
    language: "en",
    category: "science_tech",
  },
  {
    text: "What is the powerhouse of the cell?",
    answers: ["Nucleus", "Ribosome", "Golgi apparatus", "Mitochondria"],
    correctIx: 3,
    difficulty: "medium",
    language: "en",
    category: "science_tech",
  },
  {
    text: "What is the SI unit of electric current?",
    answers: ["Ampere", "Volt", "Watt", "Ohm"],
    correctIx: 0,
    difficulty: "medium",
    language: "en",
    category: "science_tech",
  },
  {
    text: "Which scientist proposed the three laws of motion?",
    answers: ["Galileo Galilei", "Isaac Newton", "Albert Einstein", "Niels Bohr"],
    correctIx: 1,
    difficulty: "medium",
    language: "en",
    category: "science_tech",
  },
  {
    text: "What is the atomic number of carbon?",
    answers: ["4", "8", "6", "12"],
    correctIx: 2,
    difficulty: "hard",
    language: "en",
    category: "science_tech",
  },
  {
    text: "What is the name of the force that opposes motion between surfaces in contact?",
    answers: ["Gravity", "Magnetism", "Inertia", "Friction"],
    correctIx: 3,
    difficulty: "hard",
    language: "en",
    category: "science_tech",
  },
  {
    text: "Who is credited with formulating the periodic law and the periodic table?",
    answers: ["Dmitri Mendeleev", "Antoine Lavoisier", "John Dalton", "Robert Boyle"],
    correctIx: 0,
    difficulty: "hard",
    language: "en",
    category: "science_tech",
  },

  // ── EN — history ──
  {
    text: "On which continent are the Pyramids of Giza located?",
    answers: ["Asia", "Africa", "Europe", "South America"],
    correctIx: 1,
    difficulty: "easy",
    language: "en",
    category: "history",
  },
  {
    text: "Which ship sank on its maiden voyage in 1912 after hitting an iceberg?",
    answers: ["Lusitania", "Britannic", "Titanic", "Queen Mary"],
    correctIx: 2,
    difficulty: "easy",
    language: "en",
    category: "history",
  },
  {
    text: "Who was the British Prime Minister during most of World War II?",
    answers: ["Winston Churchill", "Neville Chamberlain", "Clement Attlee", "Tony Blair"],
    correctIx: 0,
    difficulty: "easy",
    language: "en",
    category: "history",
  },
  {
    text: "Which ancient civilization built the Machu Picchu complex?",
    answers: ["Aztec", "Inca", "Maya", "Olmec"],
    correctIx: 1,
    difficulty: "medium",
    language: "en",
    category: "history",
  },
  {
    text: "In which year did the Berlin Wall fall?",
    answers: ["1987", "1991", "1989", "1990"],
    correctIx: 2,
    difficulty: "medium",
    language: "en",
    category: "history",
  },
  {
    text: "Who led the Indian independence movement through nonviolent civil disobedience?",
    answers: ["Jawaharlal Nehru", "Subhas Chandra Bose", "Bhagat Singh", "Mahatma Gandhi"],
    correctIx: 3,
    difficulty: "medium",
    language: "en",
    category: "history",
  },
  {
    text: "In what year did the Roman Empire's Western half fall (traditional date)?",
    answers: ["476 CE", "395 CE", "410 CE", "527 CE"],
    correctIx: 0,
    difficulty: "hard",
    language: "en",
    category: "history",
  },
  {
    text: "Which treaty officially ended World War I in 1919?",
    answers: ["Treaty of Tordesillas", "Treaty of Versailles", "Treaty of Westphalia", "Treaty of Paris"],
    correctIx: 1,
    difficulty: "hard",
    language: "en",
    category: "history",
  },
  {
    text: "Who was the first emperor of a unified China?",
    answers: ["Kublai Khan", "Han Wudi", "Qin Shi Huang", "Sun Yat-sen"],
    correctIx: 2,
    difficulty: "hard",
    language: "en",
    category: "history",
  },

  // ── EN — geography ──
  {
    text: "What is the capital city of Japan?",
    answers: ["Tokyo", "Osaka", "Kyoto", "Nagoya"],
    correctIx: 0,
    difficulty: "easy",
    language: "en",
    category: "geography",
  },
  {
    text: "Which ocean is the largest by surface area?",
    answers: ["Atlantic", "Pacific", "Indian", "Arctic"],
    correctIx: 1,
    difficulty: "easy",
    language: "en",
    category: "geography",
  },
  {
    text: "On which continent is the Sahara Desert located?",
    answers: ["Asia", "Australia", "Africa", "South America"],
    correctIx: 2,
    difficulty: "easy",
    language: "en",
    category: "geography",
  },
  {
    text: "What is the capital of Canada?",
    answers: ["Toronto", "Vancouver", "Montreal", "Ottawa"],
    correctIx: 3,
    difficulty: "medium",
    language: "en",
    category: "geography",
  },
  {
    text: "Which country is both in Europe and Asia, spanning the Bosphorus?",
    answers: ["Turkey", "Greece", "Russia", "Georgia"],
    correctIx: 0,
    difficulty: "medium",
    language: "en",
    category: "geography",
  },
  {
    text: "What is the tallest mountain in Africa?",
    answers: ["Mount Kenya", "Mount Kilimanjaro", "Mount Elgon", "Ras Dashen"],
    correctIx: 1,
    difficulty: "medium",
    language: "en",
    category: "geography",
  },
  {
    text: "Which country has the largest population in the world (as of 2024)?",
    answers: ["China", "United States", "India", "Indonesia"],
    correctIx: 2,
    difficulty: "hard",
    language: "en",
    category: "geography",
  },
  {
    text: "What is the capital of Australia?",
    answers: ["Sydney", "Melbourne", "Perth", "Canberra"],
    correctIx: 3,
    difficulty: "hard",
    language: "en",
    category: "geography",
  },
  {
    text: "Which strait separates Asia from North America?",
    answers: ["Bering Strait", "Strait of Gibraltar", "Strait of Malacca", "Strait of Hormuz"],
    correctIx: 0,
    difficulty: "hard",
    language: "en",
    category: "geography",
  },

  // ── EN — israel_local ──
  {
    text: "Which sea lies at the lowest point on Earth's land surface, bordering Israel?",
    answers: ["Dead Sea", "Red Sea", "Mediterranean Sea", "Sea of Galilee"],
    correctIx: 0,
    difficulty: "easy",
    language: "en",
    category: "israel_local",
  },
  {
    text: "What is the name of Israel's currency?",
    answers: ["Lira", "Shekel", "Dinar", "Pound"],
    correctIx: 1,
    difficulty: "easy",
    language: "en",
    category: "israel_local",
  },
  {
    text: "Which Israeli city is widely known as a major high-tech and financial hub?",
    answers: ["Eilat", "Nazareth", "Tel Aviv", "Tiberias"],
    correctIx: 2,
    difficulty: "easy",
    language: "en",
    category: "israel_local",
  },
  {
    text: "What is the name of Israel's parliament?",
    answers: ["Senate", "Knesset", "Duma", "Majlis"],
    correctIx: 1,
    difficulty: "medium",
    language: "en",
    category: "israel_local",
  },
  {
    text: "Which freshwater lake in northern Israel is also called the Sea of Galilee?",
    answers: ["Lake Hula", "Lake Ram", "Lake Kinneret", "Lake Agmon"],
    correctIx: 2,
    difficulty: "medium",
    language: "en",
    category: "israel_local",
  },
  {
    text: "Who was Israel's first female Prime Minister?",
    answers: ["Tzipi Livni", "Shulamit Aloni", "Dorit Beinisch", "Golda Meir"],
    correctIx: 3,
    difficulty: "medium",
    language: "en",
    category: "israel_local",
  },
  {
    text: "In which year was the peace treaty between Israel and Egypt signed?",
    answers: ["1979", "1973", "1982", "1977"],
    correctIx: 0,
    difficulty: "hard",
    language: "en",
    category: "israel_local",
  },
  {
    text: "Who was the first President of the State of Israel?",
    answers: ["Yitzhak Ben-Zvi", "Chaim Weizmann", "Zalman Shazar", "Ephraim Katzir"],
    correctIx: 1,
    difficulty: "hard",
    language: "en",
    category: "israel_local",
  },
  {
    text: "Which mountain is the highest peak within Israel's sovereign territory?",
    answers: ["Mount Tabor", "Mount Carmel", "Mount Meron", "Mount Gilboa"],
    correctIx: 2,
    difficulty: "hard",
    language: "en",
    category: "israel_local",
  },
];
